# Generated by Django 4.2.4 on 2023-09-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyapp', '0003_egitim_egitmen'),
    ]

    operations = [
        migrations.AddField(
            model_name='egitim',
            name='baslik_url',
            field=models.URLField(default='varsayilan_url', max_length=255),
        ),
        migrations.AddField(
            model_name='egitim',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
