# Generated by Django 4.2.4 on 2023-09-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyapp', '0004_egitim_baslik_url_egitim_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egitim',
            name='baslik_url',
            field=models.URLField(default='egitim_detay.html', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='egitim',
            unique_together={('baslik', 'slug')},
        ),
    ]
