# Generated by Django 4.2.4 on 2023-09-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyapp', '0005_alter_egitim_baslik_url_alter_egitim_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egitim',
            name='baslik_url',
            field=models.URLField(default='/egitimler/1/', max_length=255),
        ),
    ]
