# Generated by Django 4.2.4 on 2023-09-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyapp', '0007_alter_egitim_baslik_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egitim',
            name='baslik_url',
            field=models.URLField(default='/egitimler/<int:egitim_id>/', max_length=255),
        ),
    ]
