# Generated by Django 4.2.4 on 2023-09-05 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nyapp', '0008_alter_egitim_baslik_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='egitim',
            name='baslik_url',
        ),
    ]
